# Mid EXAM : Tools and Techniques Data Science 

# Task 1: ( 5 Marks)  Warp up 

# Note : Rename the file with your name and id and also mention your name and id inside here 

In [7]:
# Q1. Here, we take each element in the list a (temporarily assigning it the value i) 
a = [5, 10, 15, 20]

In [8]:
# (i)	Find the square each element in the list. This creates a new list called b and does not modify a through data comprehension.

In [9]:
b = [number**2 for number in a]
print(b)

[25, 100, 225, 400]


In [15]:
# (ii)	Write a conditional statement of only squaring the elements if the element is not equal to 10.



In [16]:
result =[i*i for i in a if i!=10]
print(result)

[25, 225, 400]


In [7]:
# Q2. (i) Write the command of random samples from a uniform distribution between 0 and 1? 

In [11]:
import numpy as np 

In [12]:
s= np.random.uniform(0,1,20)

In [13]:
#(ii)	Write the command to slice the column 1? 

In [14]:
import pandas as pd
technologies = {
    'Courses':["Spark","PySpark"],
    'Fee' :[20000,25000],
    'Duration':['30days','40days'],
    'Discount':[1000,2300]
              }
df = pd.DataFrame(technologies)
print(df)
df.loc[:, ["Courses"]]

   Courses    Fee Duration  Discount
0    Spark  20000   30days      1000
1  PySpark  25000   40days      2300


Courses
0    Spark
1  PySpark

In [17]:
#(iii)	Write the command of first and third elements in column 1?

In [25]:
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

first_element = data[0][1]
third_element = data[2][1]

print(first_element, third_element)

2 8


In [26]:
#(iv)	 Write the command of returns an 8 x 4 array

In [27]:
import numpy as np

array_8x4 = np.zeros((8, 4))
print(array_8x4)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
import pandas as pd 

In [29]:
#Q3. Create a Series that looks like this below:
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

SyntaxError: invalid syntax (Temp/ipykernel_4140/4174055471.py, line 2)

In [30]:
data = {'Flour': '4 cups',
        'Milk': '1 cup',
        'Eggs': '2 large',
        'Spam': '1 can'}

dinner_series = pd.Series(data, name='Dinner')
print(dinner_series)


Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object


In [31]:
# Q  4 Create the Data frame  as th output[27]

In [32]:
data = {'Apples': [35, 41],
        'Bananas': [21, 34]}

df = pd.DataFrame(data, index=['2017Sales', '2018Sales'])

In [27]:
df

Apples  Bananas
2017Sales      35       21
2018Sales      41       34

In [28]:
#Q4. create Dataframe then find imputation for these missing NaN in the out[47]

In [35]:
data = {
    'Age': [23.0, 39.0, 45.0, np.nan],
    'Gender': ['M', 'F', 'F', 'M'],
    'Income': [24200.0, np.nan, 45390.0, np.nan],
    'Religion': ['Muslim', 'Christian', np.nan, 'Muslim']
}

df = pd.DataFrame(data)
df


Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  Christian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [34]:
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  Christian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [39]:
#Q4(i)	Compute the appropriate missing value in income attribute?

In [36]:
# Impute missing values with mean
df['Income'].fillna(df['Income'].mean(), inplace=True)


print(df)

    Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F  34795.0  Christian
2  45.0      F  45390.0        NaN
3   NaN      M  34795.0     Muslim


In [37]:
#(ii)	Compute the appropriate missing values in religion attribute? 

In [39]:
df['Religion'].fillna('Unknown', inplace=True)

In [40]:
#(iii)	Drop the columns where any of the elements is nan

In [41]:
# Drop columns with NaN values
df = df.dropna(axis=1)

df

Gender   Income   Religion
0      M  24200.0     Muslim
1      F  34795.0  Christian
2      F  45390.0    Unknown
3      M  34795.0     Muslim

In [42]:
#(iv)	Keep only the rows with at least 2 non-na values

In [45]:
# Drop columns with NaN values
df = df.dropna(axis=1)